-- 0185_core_employee_accounts.sql — every employee can be given an account,
-- and the account is tied to their employee record (D329).
--
-- ── What the owner asked ──────────────────────────────────────────────────
--
-- *pakai email + password saja, karyawan sendiri lupa nomor mereka. biar diisi
-- email bebas — tidak perlu smtp — di treat sebagai teks biasa, biar IT yang
-- input dan generate password.* (2026-09-29, D326 answer 2)
--
-- The floor has no work email, so D325's invitation cannot reach them. IT types
-- a name and an email-shaped username, the server generates a password, and IT
-- hands it over. The address is never mailed.
--
-- And `ops_hr.employees.user_id` (0152) is read by `my_employee_id()` and
-- written by nothing: `/profil` told people to *ask HRD to link this account*,
-- and there was nowhere to do it (F183, F186).
--
-- ── What this adds ────────────────────────────────────────────────────────
--
-- 1. `ops_core.create_user` — the decision to make an account IT will give a
--    password to. The same rules as `invite_user`, which now shares them
--    (`new_account_problem`), so the two ways in cannot disagree about what a
--    valid new account is. `/api/identity/users` asks GoTrue's admin API to
--    create it (`email_confirm: true`, a generated password) only on ok.
-- 2. `ops_core.request_user_password` — the decision to give an account a new
--    password. The trail says a password was reset and by whom. **The password
--    itself never reaches the database**: it is generated by the server after
--    this answers, sent to GoTrue, and shown once to IT. No table, trail row,
--    activity event or outbox payload holds it.
-- 3. `request_user_link` refuses an address under `.local` — the convention
--    for an account with no mailbox (D329). GoTrue accepts such an address for
--    an account (its admin API checks the format only), and its own mail
--    validation refuses to send to it; saying so here says *make a new
--    password instead*, rather than GoTrue's sentence about DNS.
-- 4. `ops_hr.link_employee_account` — link an account to an employee, or
--    unlink it. IT does the input (the owner's words), so it is
--    `it.manage_users`, as every other act on a person's account (D325).
-- 5. `ops_hr.v_employee_account` (over `employee_accounts()`) — who has which account, for the two screens
--    that ask: IT → Pengguna & akses (search by name or number, see the link)
--    and HR → Karyawan (read-only). Name, number, unit, position and whether
--    they still work here — nothing about pay.
--
-- ── What this deliberately does not do ────────────────────────────────────
--
-- It does not change the shell's `/no-access` gate. An account made this way
-- holds no module (D24); D331 lets a linked, module-less account into `/saya`.
--
-- It does not store which accounts have a mailbox. The `.local` convention is
-- the whole of that fact, and it is readable from the address.

-- ── 1. one rule for a new account ─────────────────────────────────────────
--
-- A helper the two seams call, returning the refusal (already written to the
-- trail) or null. The action is the caller's, so the
-- trail says *invite* or *create* for the road actually taken.
create or replace function ops_core.new_account_problem(
  p_email text, p_full_name text, p_action text)
returns jsonb
language plpgsql security definer set search_path = ops_core, pg_temp as $$
declare
  v_email    text := lower(btrim(coalesce(p_email, '')));
  v_name     text := btrim(regexp_replace(coalesce(p_full_name, ''), '\s+', ' ', 'g'));
  v_existing ops_core.users;
begin
  if not ops_core.has_permission('it.manage_users') then
    return ops_core.refused('identity','user', nullif(v_email, ''), p_action,
      'authority_required',
      'Adding somebody to this workspace belongs to IT — logged, not applied.',
      jsonb_build_object('required','it.manage_users'));
  end if;

  if v_email !~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$' then
    return ops_core.invalid('identity','user', nullif(v_email, ''), p_action,
      'email_invalid', 'That is not an email address.',
      jsonb_build_object('field','email'));
  end if;
  if v_name = '' then
    return ops_core.invalid('identity','user', v_email, p_action,
      'name_required', 'A name is required — it is what every approval and payslip shows.',
      jsonb_build_object('field','full_name'));
  end if;
  if length(v_name) > 120 then
    return ops_core.invalid('identity','user', v_email, p_action,
      'name_too_long', 'A name is at most 120 characters.',
      jsonb_build_object('field','full_name', 'max', 120));
  end if;

  select * into v_existing from ops_core.users where email = v_email::ops_core.citext;
  if found then
    return ops_core.conflict('identity','user', v_email, p_action,
      'already_registered', 'That address already has an account here.',
      jsonb_build_object('user_id', v_existing.id, 'is_active', v_existing.is_active));
  end if;

  if exists (select 1 from auth.users a where lower(a.email) = v_email) then
    return ops_core.conflict('identity','user', v_email, p_action,
      'already_registered',
      'That address already has a sign-in but no profile yet. It is created the first time they sign in.',
      jsonb_build_object('profile', false));
  end if;

  return null;
end $$;

-- Granted like every seam (A2_core_execute_grants): it decides inside, and
-- all it can do for a caller without `it.manage_users` is refuse them.
revoke execute on function ops_core.new_account_problem(text, text, text) from public;
grant execute on function ops_core.new_account_problem(text, text, text) to authenticated;

-- `0183`'s body, with its checks moved into the helper. Same answers.
create or replace function ops_core.invite_user(p_email text, p_full_name text)
returns jsonb
language plpgsql security definer set search_path = ops_core, pg_temp as $$
declare
  v_problem jsonb := ops_core.new_account_problem(p_email, p_full_name, 'invite');
begin
  if v_problem is not null then return v_problem; end if;
  return ops_core.ok('identity','user', lower(btrim(p_email)), 'invite',
    jsonb_build_object('email', lower(btrim(p_email)),
                       'full_name', btrim(regexp_replace(p_full_name, '\s+', ' ', 'g'))));
end $$;

-- The decision to make an account with a password IT generates (D329).
--
-- Like `invite_user`, nothing is written here but the trail; GoTrue creates
-- the account on ok and `provision_user` makes the profile, holding nothing
-- (D24). The trail says *create*, not *invite*: nobody was mailed.
create or replace function ops_core.create_user(p_email text, p_full_name text)
returns jsonb
language plpgsql security definer set search_path = ops_core, pg_temp as $$
declare
  v_problem jsonb := ops_core.new_account_problem(p_email, p_full_name, 'create');
begin
  if v_problem is not null then return v_problem; end if;
  return ops_core.ok('identity','user', lower(btrim(p_email)), 'create',
    jsonb_build_object('email', lower(btrim(p_email)),
                       'full_name', btrim(regexp_replace(p_full_name, '\s+', ' ', 'g'))));
end $$;

-- ── 2. a new password, decided here and made elsewhere ────────────────────
--
-- **Never your own.** IT's own password is changed on `/profil`, where the
-- old one is asked for; a button that hands its presser a fresh password for
-- their own account is a way around that.
--
-- Refused for a switched-off account, for `request_user_link`'s reason: a
-- password into an account that holds nothing opens nothing.
create or replace function ops_core.request_user_password(p_user_id uuid)
returns jsonb
language plpgsql security definer set search_path = ops_core, pg_temp as $$
declare
  v_target ops_core.users;
begin
  if not ops_core.has_permission('it.manage_users') then
    return ops_core.refused('identity','user', p_user_id::text, 'password.reset',
      'authority_required',
      'Giving somebody a new password belongs to IT — logged, not applied.',
      jsonb_build_object('required','it.manage_users'));
  end if;

  if p_user_id = auth.uid() then
    return ops_core.refused('identity','user', p_user_id::text, 'password.reset',
      'self_service_refused',
      'Change your own password on your profile page.');
  end if;

  select * into v_target from ops_core.users where id = p_user_id;
  if not found then
    return ops_core.not_found('identity','user', p_user_id::text, 'password.reset',
      'No such user.');
  end if;

  if not v_target.is_active then
    return ops_core.refused('identity','user', v_target.email, 'password.reset',
      'user_inactive',
      'Switch the account back on first — a password into an account that holds nothing opens nothing.');
  end if;

  return ops_core.ok('identity','user', v_target.email, 'password.reset',
    jsonb_build_object('user_id', p_user_id, 'email', v_target.email,
                       'full_name', v_target.full_name));
end $$;

-- ── 3. no link to an address that is not a mailbox ───────────────────────
--
-- `0183`'s body with one refusal added before the answer.
create or replace function ops_core.request_user_link(p_user_id uuid)
returns jsonb
language plpgsql security definer set search_path = ops_core, pg_temp as $$
declare
  v_target    ops_core.users;
  v_confirmed timestamptz;
  v_known     boolean;
begin
  if not ops_core.has_permission('it.manage_users') then
    return ops_core.refused('identity','user', p_user_id::text, 'link.send',
      'authority_required',
      'Sending somebody a sign-in link belongs to IT — logged, not applied.',
      jsonb_build_object('required','it.manage_users'));
  end if;

  select * into v_target from ops_core.users where id = p_user_id;
  if not found then
    return ops_core.not_found('identity','user', p_user_id::text, 'link.send',
      'No such user.');
  end if;

  if not v_target.is_active then
    return ops_core.refused('identity','user', v_target.email, 'link.send',
      'user_inactive',
      'Switch the account back on first — a link into an account that holds nothing opens nothing.');
  end if;

  if lower(v_target.email::text) like '%.local' then
    return ops_core.refused('identity','user', v_target.email, 'link.send',
      'no_mailbox',
      'This address is a username, not a mailbox — nothing can be sent to it. Make a new password instead.');
  end if;

  select a.email_confirmed_at, true into v_confirmed, v_known
    from auth.users a where a.id = p_user_id;

  return ops_core.ok('identity','user', v_target.email, 'link.send',
    jsonb_build_object(
      'user_id', p_user_id,
      'email', v_target.email,
      'full_name', v_target.full_name,
      'kind', case when coalesce(v_known, false) and v_confirmed is null then 'invite'
                   else 'recovery' end));
end $$;

-- ── 4. the link between an account and an employee ────────────────────────
--
-- `p_user_id` null unlinks. Keyed by the employee, because that is the row
-- the column is on and the one `my_employee_id()` reads.
--
-- Refused, each with the name of the other side so the screen can say where
-- the account or the person already is:
--   employee_has_account     the employee is linked to another account
--   account_linked_elsewhere the account is linked to another employee
--   employee_left            linking somebody who no longer works here
-- The column is unique, so the second would raise; answering it first keeps
-- the refusal in the trail (0003: an exception rolls its own audit row back).
--
-- Unlinking is never refused for a left employee or a switched-off account:
-- undoing a mistake has to stay possible whatever else changed.
create or replace function ops_hr.link_employee_account(p_employee_id uuid, p_user_id uuid)
returns jsonb
language plpgsql security definer set search_path = ops_hr, ops_core, pg_temp as $$
declare
  v_emp    ops_hr.employees;
  v_user   ops_core.users;
  v_other  ops_hr.employees;
  v_before ops_core.users;
  v_action text := case when p_user_id is null then 'account.unlink' else 'account.link' end;
begin
  if not ops_core.has_permission('it.manage_users') then
    return ops_core.refused('hr','employee', p_employee_id::text, v_action,
      'authority_required',
      'Linking an account to an employee belongs to IT — logged, not applied.',
      jsonb_build_object('required','it.manage_users'));
  end if;

  select * into v_emp from ops_hr.employees where id = p_employee_id;
  if not found then
    return ops_core.not_found('hr','employee', p_employee_id::text, v_action,
      'No such employee.');
  end if;

  if v_emp.user_id is not null then
    select * into v_before from ops_core.users where id = v_emp.user_id;
  end if;

  -- ── unlink ──
  if p_user_id is null then
    if v_emp.user_id is null then
      return ops_core.noop('hr','employee', v_emp.employee_no, v_action,
        'This employee has no account linked.',
        jsonb_build_object('employee_id', v_emp.id, 'user_id', null));
    end if;
    update ops_hr.employees set user_id = null, updated_at = now() where id = v_emp.id;
    return ops_core.ok('hr','employee', v_emp.employee_no, v_action,
      jsonb_build_object('employee_id', v_emp.id, 'employee_no', v_emp.employee_no, 'user_id', null),
      jsonb_build_object('user_id', v_emp.user_id, 'email', v_before.email),
      jsonb_build_object('user_id', null));
  end if;

  -- ── link ──
  select * into v_user from ops_core.users where id = p_user_id;
  if not found then
    return ops_core.not_found('hr','employee', v_emp.employee_no, v_action,
      'No such account.');
  end if;

  if v_emp.user_id = p_user_id then
    return ops_core.noop('hr','employee', v_emp.employee_no, v_action,
      'This account is already linked to this employee.',
      jsonb_build_object('employee_id', v_emp.id, 'user_id', p_user_id));
  end if;

  if v_emp.user_id is not null then
    return ops_core.conflict('hr','employee', v_emp.employee_no, v_action,
      'employee_has_account',
      format('%s is already linked to %s. Unlink that account first.', v_emp.full_name, v_before.email),
      jsonb_build_object('employee_id', v_emp.id, 'user_id', v_emp.user_id, 'email', v_before.email));
  end if;

  select * into v_other from ops_hr.employees where user_id = p_user_id;
  if found then
    return ops_core.conflict('hr','employee', v_emp.employee_no, v_action,
      'account_linked_elsewhere',
      format('%s is already linked to %s (%s). Unlink it there first.',
             v_user.email, v_other.full_name, v_other.employee_no),
      jsonb_build_object('employee_id', v_other.id, 'employee_no', v_other.employee_no,
                         'full_name', v_other.full_name));
  end if;

  if not v_emp.active then
    return ops_core.refused('hr','employee', v_emp.employee_no, v_action,
      'employee_left',
      format('%s no longer works here — an account for them would open nothing of theirs.', v_emp.full_name),
      jsonb_build_object('employee_id', v_emp.id, 'left_on', v_emp.left_on));
  end if;

  update ops_hr.employees set user_id = p_user_id, updated_at = now() where id = v_emp.id;

  return ops_core.ok('hr','employee', v_emp.employee_no, v_action,
    jsonb_build_object('employee_id', v_emp.id, 'employee_no', v_emp.employee_no, 'user_id', p_user_id),
    jsonb_build_object('user_id', null),
    jsonb_build_object('user_id', p_user_id, 'email', v_user.email));
end $$;

revoke execute on function ops_core.create_user(text, text) from public;
revoke execute on function ops_core.request_user_password(uuid) from public;
revoke execute on function ops_hr.link_employee_account(uuid, uuid) from public;
grant execute on function ops_core.create_user(text, text) to authenticated;
grant execute on function ops_core.request_user_password(uuid) to authenticated;
grant execute on function ops_hr.link_employee_account(uuid, uuid) to authenticated;

-- ── 5. who has which account ──────────────────────────────────────────────
--
-- Neither reader can see the other half under its own RLS: IT has no
-- `hrd.read` for the roster, and HR cannot read another person's row in
-- `ops_core.users`. So a definer function answers exactly the columns the link
-- needs, to exactly those two, and nothing about pay — and the view over it is
-- an ordinary invoker view. Not a third owner-rights view: `17_core_view_invoker`
-- keeps those to the two that say what somebody may open (the `approvers()`
-- shape, 0159).
create or replace function ops_hr.employee_accounts()
returns table (
  employee_id uuid, employee_no text, full_name text, "position" text, unit text,
  active boolean, user_id uuid, user_email text, user_full_name text, user_is_active boolean)
language sql stable security definer set search_path = ops_hr, ops_core, pg_temp as $$
  select e.id, e.employee_no, e.full_name, e.position, e.unit, e.active,
         e.user_id, u.email::text, u.full_name, u.is_active
    from ops_hr.employees e
    left join ops_core.users u on u.id = e.user_id
   where ops_core.has_permission('it.read')
      or ops_core.has_permission('hrd.read')
$$;

revoke execute on function ops_hr.employee_accounts() from public;
grant execute on function ops_hr.employee_accounts() to authenticated;

create or replace view ops_hr.v_employee_account
  with (security_invoker = on) as
  select * from ops_hr.employee_accounts();

grant select on ops_hr.v_employee_account to authenticated;

comment on function ops_core.create_user is
  'The decision to make an account IT gives a generated password to. Writes only the trail; '
  '/api/identity/users creates it in GoTrue (email_confirm, no mail) on ok. (0185, D329)';
comment on function ops_core.request_user_password is
  'The decision to give an account a new password. it.manage_users; never your own; refused '
  'for an inactive account. The password never reaches the database. (0185, D329)';
comment on function ops_hr.link_employee_account is
  'Link an account to an employee (p_user_id null unlinks). it.manage_users. Refuses an '
  'employee already linked, an account linked elsewhere, and a left employee. (0185, D329)';

analyze ops_hr.employees;
